# Use Docker-based container (instead of OpenVZ)
sudo: false
language: scala
scala:
- 2.11.8
- 2.12.0-RC2
jdk: oraclejdk8
script: ./.ci/run.sh

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.coursier
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

before_install:
- pip install --user codecov

env:
  global:
  - COURSIER_NO_TERM=1
